version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout: 
      - run: 
          name: Gradle Test
          command: |
           gradle test
           gradle jar
      - store_artifacts:
         path: /code/test-results
         destination: prefix
