version: 2.0
jobs:
  initialTest:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: gradle test
      - store_test_results:
          path: test-results
  runGradleJar:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: gradle jar
      - store_artifacts:
          path: /code/test-results
          destination: prefix
  build:
    machine: true
    steps:
      - checkout:
    # login to docker:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    #build the image
      - run: docker build -t gohomeapp:$CIRCLE_SHA1 .

    # deploy the image 
      - run: docker push vintherwolf/gohomeapp_@CIRCLE_SHA1

workflows:
  version: 2
  jobSequence:
    jobs:
      - initialTest:
          filters:
            branches:
              only:
                - master
      - runGradleJar:
          requires:
            - initialTest
      - build:
          filters:
            branches:
              only: 
                - master
          requires:
            - initialTest
            - runGradleJar
