version: 2.0
jobs:
  initialTest:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: gradle test
      - store_test_results:
          path: test-results
  runGradleJar:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: gradle jar
      - store_artifacts:
          path: /code/test-results
          destination: prefix
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          command: gradle jar
      - store_artifacts:
          path: /code/test-results
          destination: prefix

workflows:
  version: 2
  jobSequence:
    jobs:
      - initialTest:
          filters:
            branches:
              only:
                - master
      - runGradleJar:
          requires:
            - initialTest
      - build:
          filters:
            branches:
              only: 
                - master
          requires:
            - initialTest
            - runGradleJar
