version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout: https://circleci.com/gh/VintherWolf/circle-ci-workshop/
      - run: gradle
          name: Gradle Test
          command: |
            gradle test
